[package]
name = "text-hook"
version = "1.0.0"
edition = "2024"
license = "MIT"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[features]

# features ---------------------------------------------------

# 如下 bind_* 系列 feature 将特定组件绑定到 HookImplType--------

# 启用资产虚拟化文件系统，Hook CreateFile 相关函数，如果命中到资源包里的资产文件，会重定向到资源包临时目录
bind_asset_virtualizer = ["enable_resource_pack"]
# Hook CreateFont 相关函数实现字体管理，使用 disable_forced_font 控制字体过滤的行为
bind_font_manager = []
# 通过 HOOK ExitProcess 以及相关函数
# 实现对应于 PROCESS_ATTACH 阶段的清理工作
# 默认不会执行清理，因为进程内资源系统可以正确进行清理回收
bind_lifecycle_guard = ["enable_attach_cleanup"]
# Hook `CreateFileA`，将匹配 `REDIRECTION_SRC_PATH` 的文件重定向到 `REDIRECTION_TARGET_PATH`
# 目前的实现十分简陋，需要确保 `REDIRECTION_SRC_PATH`，`REDIRECTION_TARGET_PATH`均为ascii
bind_path_redirector = []
# Hook `GDI` 相关的绘制函数，并将文本中的替身字符转换为正常字符，映射表由`translate_macros::generate_mapping_data!`生成
# 使用 assume_text_out_arg_c_is_byte_len，将认为输入参数C是字节长度而不是字符长度
bind_text_mapping = []
bind_user_interface_patcher = ["enable_text_patch"]
# 绑定 overlay egui I/O 处理器
# 目前无法正确处理 OverlayWndProc 重入产生的消息，因为 RefCell 的限制
bind_egui_io = ["enable_overlay_egui"]
# 绑定默认的 overlay egui UI 渲染器，显示所有组件并提供组件可见性控制面板
bind_egui_default_ui = ["enable_overlay_egui"]
# Hook `DefWindowProc` 并对窗口标题进行处理，
# 如果开启了 enable_window_title_override，使用`assets/config.json`的`WINDOW_TITLE`覆写标题
# 否则将其根据 ANSI_CODE 转码为u16并进行映射处理，然后传递给 W 版本的 DefWindowProc
bind_window_title_overrider = []

# 开启 egui 日志组件的支持
enable_egui_logger = ["enable_overlay_egui", "enable_debug_output"]
# 开启 egui demo 组件的支持
enable_egui_demo = ["enable_overlay_egui"]

# 开启后，仅对命中过滤器的字体执行替换；未命中过滤器的字体保持原样。
# 此时 `FONT_FILTER` 的语义等价于黑名单，而不是白名单。
disable_forced_font = []
# 假设TextOutA中的`c`参数是字节而不是字符数
# 对于一些传入了错误的参数的老游戏可能会有效...
assume_text_out_arg_c_is_byte_len = []
# 使用`assets/config.json`的`WINDOW_TITLE`字段覆写游戏主窗口标题
enable_window_title_override = []

# 调试输出
enable_debug_output = []
# 调试输出映射文本
enable_text_mapping_debug = ["enable_debug_output"]

# 读取x64dbg的1337文件并生成运行时patch代码
enable_x64dbg_1337_patch = []
# 是否在Process attach时自动应用1337补丁
auto_apply_1337_patch_on_attach = ["enable_x64dbg_1337_patch"]
# 使用硬件断点中断目标位置(通过constants生成)，中断时应用x64dbg补丁文件
auto_apply_1337_patch_on_hwbp_hit = [
    "enable_hwbp_from_constants",
    "enable_x64dbg_1337_patch",
]

# 对应于 PROCESS_ATTACH 阶段的清理工作
# 默认不会执行清理，因为进程内资源系统可以正确进行清理回收
enable_attach_cleanup = []
# 启用 overlay 的 egui 集成，依赖 OpenGL overlay
enable_overlay_egui = ["enable_overlay_gl", "dep:egui", "dep:egui_glow"]
# 启用 overlay 的 轻量级 OpenGL 绘制器集成，依赖 OpenGL overlay
enable_overlay_gl_painter = ["enable_overlay_gl", "enable_gl_painter"]
# 启用独立透明覆盖层，使用 OpenGL 绘制
enable_overlay_gl = ["enable_overlay"]
# 启用独立透明覆盖层（同进程）
enable_overlay = ["enable_win_event_hook", "enable_worker_thread"]
# 启用轻量的 OpenGL 绘制器
enable_gl_painter = []
# 窗口事件钩子(windows的SetWinEventHook的钩子机制)
enable_win_event_hook = ["enable_worker_thread"]
# 在DLL attach的时候创建一个工作线程
enable_worker_thread = []
# 延迟加载，使用硬件断点中断目标位置(通过constants生成)
enable_hwbp_from_constants = ["enable_veh", "enable_delayed_attach"]
# 启用 veh 处理程序，可用于捕获硬件断点
enable_veh = []
# 扫描 assets/resource_pack 生成资源包
# 在DLL attach时，会将资源包解压到临时目录中
# 在DLL detach时，会将临时目录删除
# 若exe所在目录的同名文件存在于临时目录中
# 则重定向到临时目录中，否则直接转发
enable_resource_pack = ["dep:path-clean"]
# 内嵌资源包而不是外置
embed_resource_pack = ["enable_resource_pack"]
# 使用IAT HOOK，而不是Inline Hook
# IAT HOOK 比 Inline Hook更轻量，但是后者更全面
enable_iat_hook = []

# 截获并替换文本数据
enable_text_patch = []
# 提取文本而不是替换文本，需要开启 bind_lifecycle_guard 或者显式调用 cleanup 才能将原文输出
extract_text = ["enable_text_patch", "enable_attach_cleanup"]
# 截获并替换patch数据
enable_patch = []
# 提取补丁而不是替换补丁
extract_patch = ["enable_patch"]

# 嵌入`assets/font`的自定义字体，会使用`AddFontMemResourceEx`让GDI识别
enable_custom_font = []
# 导出默认的DllMain，内部使用`default_dll_main`，
# 使用`HookImplType::default()`作为钩子实例
export_default_dll_main = []
# 模拟日语环境，基于locale_emulator
enable_locale_emulator = []
# 启用延迟加载，对于某些特性是必要的
enable_delayed_attach = []
# 根据`assets/hijacked`中的PE文件(仅限一个)生成对应的导出函数，
# 以进行DLL劫持，编译后需要自己改名为对应的DLL文件名，然后放在游戏EXE所在的目录。
# 在`assets/config.json`的`HIJACKED_DLL_PATH`中可以指定被劫持DLL的路径，
# 否则默认会在系统目录中寻找
enable_dll_hijacking = ["enable_delayed_attach"]

# 是否导出钩子函数，实际上如果用detour的话，不需要导出
export_hook_symbols = []


# 通用impl ---------------------------------------------------

# 默认的HOOK实现(即使用`Hook` trait的默认代码)，并导出默认的DllMain
default_impl = ["export_default_dll_main"]

# 针对特定游戏的impl-------------------------------------------
# 非C社的c4
c4 = [
    "enable_patch",
    "default_impl",
    "bind_text_mapping",
    "bind_font_manager",
    "disable_forced_font",
]
complets = [
    "export_default_dll_main",
    "bind_text_mapping",
    "bind_font_manager",
    "disable_forced_font",
    "assume_text_out_arg_c_is_byte_len",
    "bind_window_title_overrider",
]
natsu_natsu = [
    "export_default_dll_main",
    "bind_text_mapping",
    "bind_font_manager",
    "disable_forced_font",
]
seraph = ["export_default_dll_main"]
g0win = ["export_default_dll_main", "enable_text_patch"]
hitocos2 = ["export_default_dll_main", "enable_text_patch"]

[dependencies]
translate-macros.workspace = true
serde.workspace = true
serde_json.workspace = true

windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_HiDpi",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_OpenGL",
    "Win32_UI_Accessibility",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
    "Win32_System_SystemInformation",
    "Win32_Globalization",
    "Win32_System_Console",
    "Win32_System_ProcessStatus",
    "Win32_System_IO",
    "Win32_Security",
    "Win32_System_Registry",
    "Win32_System_SystemServices",
    "Win32_System_WindowsProgramming",
    "Win32_Storage_FileSystem",
    "Win32_UI_Controls",
    "Win32_System_Kernel",
    "Win32_System_Environment",
] }
sha2 = "0.10"
retour = { git = "https://github.com/renamed23/retour-rs", branch = "self-use" }
phf = { version = "0.13", features = ["macros"] }
indexmap = { version = "2", features = ["serde"] }
ntapi = "0.4"
scopeguard = "1"
const-str = "1"
path-clean = { version = "1", optional = true }
ruzstd = "0.8"
glow = "0.16"
bytemuck = { version = "1.25", features = ["derive"] }
cfg-if = "1.0"
egui = { version = "0.33.3", optional = true, default-features = false }
egui_glow = { version = "0.33.3", optional = true }

[build-dependencies]
anyhow.workspace = true

[lints.clippy]
too_many_arguments = "allow"
